config:
 server_name: server1 
 ipaddress: x.x.x.x
 password: better
 username: root
 port: 8899
 folder_array: "/app/server1,/backup/mysqlback,/etc/httpd"
 backup_path: '/data/current_backups/server1'
 exclude_array: "log/*,*bak,.log"
 schedule: "daily,hourly"
