config:
 server_name: test2
 ipaddress: x.x.x.x
 password: better
 username: root
 port: 22
 folder_array: "/data/rcprosdsdduction:daily|hourly,/data/babsdadywisdsdsadadeguides,/backup/mysqlbackup/,/etc/httpd"
 backup_path: '/data/current_backups/test2'
 exclude_array: "log/*,*bak,.log"
 schedule: "hourly,daily"
