config:
 server_name: server3
 ipaddress: x.x.x.x
 password: better
 username: root
 port: 8899
 folder_array: "/app/data,app_mysqldata"
 backup_path: '/data/current_backups/server3'
 exclude_array: "log/*,*bak,.log"
 schedule: "daily"
