config:
 server_name: test3
 ipaddress: x.x.x.x
 password: better
 username: root
 port: 22
 folder_array: "/app/pgtest3,/app/test3hq,/app/test3ntracker,/backup/mysqlbackup,/backup/pgsql_backup,/etc/httpd,/etc/postfix"
 backup_path: '/data/current_backups/test3hq'
 exclude_array: "*bak,.log"
 schedule: "daily,hourly"
